### ISSUE TITLE
Request executor error message contains the string "[object Object]"

### ISSUE THREAD

**Issue by greim** [stormpath/stormpath-sdk-node#160]
Using node 0.12 on Ubuntu, I've seen error messages like this:

```
Unable to execute http request [object Object]: getaddrinfo ENOTFOUND api.stormpath.com
```

Originating here: https://github.com/stormpath/stormpath-sdk-node/blob/master/lib/ds/RequestExecutor.js#L90

It's a minor issue, but it might help debugging if it included more specific info about the `req` object, such as the method and URL.

**Comment by rdegges** [comment]
We definitely need to improve the error handling around some of our HTTP stuff internally.

The error you're receiving is happening because of a DNS issue on your API client, but we have some really nice exponential backoff stuff in the works that will (hopefully) prevent this sort of thing from happening as frequently.

Thanks for the report!

**Comment by greim** [comment]
Thanks for the response.

> exponential backoff

Out of curiosity, how would that work? Since we initiate these calls using a Stormpath client method, would it detect DNS failures specifically and retry the call in those cases, transparently to the caller?

**Comment by rdegges** [comment]
No -- what it'll do is basically retry any failed HTTP requests.

So if try #1 fails, it'll wait a bit and try again. If that fails, it'll wait a bit longer and try again. Basically it'll have 3 - 4 re-attempts.

Finally, if nothing works, it'll throw the appropriate error.

**Comment by greim** [comment]
Nice! Thanks for the info.
