### ISSUE TITLE
Ability to specify an organization nameKey as an accountStore for loginAttempt

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-sdk-node#201]

**Comment by typerandom** [comment]
@omgitstom Could you add some more details on how you'd like this to work?

**Comment by robertjd** [comment]
This refers to the function `Application.authenticateAccount`.  Right now it accepts an `accountStore` property.  If that property is a string we apply that to the resulting `accountStore` object as an href.  Otherwise we just pass the object along if the input is an object (and not a string).

I think all we need to do is document how you can pass in an object that looks like this:

```
application.authenticateAccount({
  username:'',
  password: ''
  accountStore: {
    nameKey: 'the name key'
  }
});
```
