### ISSUE TITLE
OAuthAuthenticator does not propagate info for local validation to JwtAuthenticator

### ISSUE THREAD

**Issue by asargento** [stormpath/stormpath-sdk-node#216]
On lib/oauth/authenticator.js, the information for local validation is not correctly propagated to JwtAuthenticator.

**Comment by robertjd** [comment]
This is a bug, thank you for the report.  I'm filing it for the upcoming patch release.

**Comment by typerandom** [comment]
@robertjd I have been looking at this, and thought after our talk that I had figured out what to do. But when I dug into it I discovered that I still felt a bit dumb since I couldn't figure out exactly what was wrong or "missing":) I.e. what is expected that needs to be passed from OAuthAuthenticator to JwtAuthenticator that currently isn't being passed?

**Comment by robertjd** [comment]
This property:

https://github.com/stormpath/stormpath-sdk-node/blob/master/lib/jwt/jwt-authenticator.js#L22

Is not assigned if the JwtAuthenticator is constructed by the OAuthAuthenticator:

https://github.com/stormpath/stormpath-sdk-node/blob/abe164b88538cf357c18ac53545796cd48fa0e03/lib/oauth/authenticator.js#L38

**Comment by typerandom** [comment]
Ah, that was way too simple :)
