### ISSUE TITLE
Cache does not work for access tokens

### ISSUE THREAD

**Issue by asargento** [stormpath/stormpath-sdk-node#217]
The cache for the access tokens is not working properly.
The cache key used is something like 'https://api.stormpath.com/v1/accessTokens/xxxxx' (the resource href).
But, on JwtAuthenticator (line 52), the cache key that is used has the '/applications/xxxx' part
```javascript
// If the KID exists, this was issued by our API
var href = self.application.href + '/authTokens/' + token;
```

**Comment by robertjd** [comment]
We intentionally do not cache `accessToken` resources in the SDK.  The reason is this use case: an access token has been revoked, but the SDK has a cached copy.  That cached copy can still be used for authentication, even though it has been revoked.  The SDK must make a request to api.stormpath.com in order to know if the token still exists and hasn't been revoked.

However, we understand that you may want to rely on a local validation and don't want or need to make a roundtrip request to the Stormpath API.  In that situation you should use "local validation", which you can enable like so:

```
new JwtAuthenticator(application).withLocalValidation();
```

I understand that this is not yet documented, my apologies for that (I'm going to create an issue for that now).  When local validation is enabled, we assert that the token is signed by your application and that it is not expired.  If those conditions are true we allow authentication, without another request of the Stormpath API.
