### ISSUE TITLE
Add DynamoDb cache store

### ISSUE THREAD

**Issue by jcwayne** [stormpath/stormpath-sdk-node#296]
For many using AWS, this is a better option than ElastiCache (either Redis or Memcached).

**Comment by rdegges** [comment]
I'm a huge DynamoDB fan (been using it for yearssss), but unfortunately, it isn't a good cache solution for a product like Stormpath. The reason is that (currently) the maximum item size is 400KB: http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Limits.html

In Stormpath, all resources can store CustomData up to 10MB per resource, which means that using DynamoDB would fundamentally break a lot of caching for many users using customData :(
