### ISSUE TITLE
please add example objects returned from methods to your documentation, and document all options for each method

### ISSUE THREAD

**Issue by r3wt** [stormpath/stormpath-sdk-node#510]

**Comment by robertjd** [comment]
Hi @r3wt , I feel your pain :(  which is why I'm re-writing everything with JsDoc :)  We're tracking the work with #149.

It's almost done, but if you want to start using it now, you can close this repo and checkout the `jsdoc-wip` branch, and then run `./docs-dev.sh` in the root of the repo.  That will pop open a HTTP server with the documentation.

Best,
Robert

**Comment by edjiang** [comment]
Scanning through these -- the new docs have been out for the past week or two! Link: https://docs.stormpath.com/nodejs/jsdoc/

**Comment by r3wt** [comment]
@edjiang awesome! Thank you for your hard work.

**Comment by edjiang** [comment]
No problem! It's actually @robertjd, @timothyej, and @typerandom who put in all the work to document the node SDK -- I just noticed this issue still open and thought I'd clean up the outstanding issue =]

**Comment by r3wt** [comment]
Ok ed, noted. Thanks to you guys for working hard, @robertjd , @timothyej , and @typerandom for this hard work!
