### ISSUE TITLE
Can't click on text in sidebar on API Docs

### ISSUE THREAD

**Issue by edjiang** [stormpath/stormpath-sdk-node#518]
Tested in both Safari and Chrome, ya'll Safari haters ;]

![screen shot 2016-08-08 at 11 52 26 am](https://cloud.githubusercontent.com/assets/918770/17491966/a42d1016-5d5e-11e6-86eb-2447d5ab7f91.png)

Test: click on text in API reference on right side of guide. It will not scroll to function.

Expected: it will scroll to the function definition.

Aside: clicking on the background (but not the text) has expected behavior.

**Comment by typerandom** [comment]
The exact error seems to be a JSDoc one. I.e. when you click outside of the text, the click event is on a `span`-element which is missing a href attribute that it expecting to be there. Clicking directly on the text triggers the click event on the `a`-element with the `href` attribute present, which is why clicking directly on the text works. Unfortunately we're currently unable to build JSDoc for the moment (build errors when running `npm run docs`). So I'm going to put this one back in open.
